export const projects = [
  {
    title: 'Good and Bad Oil Palm Seed Detection with ML methods',
    description: "Using various libraries for machine learning methods and data representation, helped with identifying good seeds from bad seeds in a dataset of palm oil seeds",
      image: '/images/prod-1.png',
      tags: ['Python', 'Scikit Learn'],
    source: 'https://colab.research.google.com/drive/1aZ0Wdmqd9gpryLmwCZL-Ss6S1M5RCHmY',
    visit: '',
    sourceName: 'Google Colab',
    visitName:'',
    id: 0,
  },
  {
    title: 'Final Year Project - Emotion Detection of EEG Signals Using Soft Voting Based Ensemble of Classifiers',
    description:"In my FYP, I have taken on a research project about emotion detection with EEG signals, using DEAP dataset for classification of emotion. Above image shows the high-level diagram of proposed method. More details in report and code.",
    image: '/images/prod-2.png',
    tags: ['MATLAB', 'Python', 'Scikit Learn'],
    source: 'https://colab.research.google.com/drive/1vf8ekkhRiRHsAfjwZmUa91TtxaBR0jb9?usp=sharing',
    visit: '',
    sourceName: 'Google Colab',
    visitName:'',
    id: 1,
  },
  {
    title: 'Worm Detection with Image Processing Methods',
    description: "Using basic Image Processing methods, the detection of worm as well as informations of the worm has been extracted in a set of images.",
      image: '/images/prod-4.png',
      tags: ['MATLAB'],
    source: '',
    visit: '',
    sourceName: 'Github',
    visitName:'',
    id: 2,
  },
  {
    title: 'E-commerce mobile application',
    description: "Using React Native as well as many libraries, I have lead the front-end development of state management as well as the inner workings of the application during an internship.",
    image: '/images/prod-9.png',
    tags: ['React Native', 'Firebase', 'Javascript'],
    source: '',
    visit: '',
    sourceName: '',
    visitName:'',
    id: 3,
  },
  {
    title: 'Durian Garden DBMS',
    description: "Using Django as the framework of our webapp and mySQL for the backend of the webapp - This management system is proposed by my client (Durian Garden Sdn. Bhd.) aimed to improve the company's workflow efficiency and reduce the cost for managing their inventory.",
    image: '/images/prod-6.png',
    tags: ['Python', 'Django', 'MySQL'],
    source: 'https://github.com/jackuson14/DGSB-Stock-Management-Project',
    visit: '',
    sourceName: 'Github',
    visitName:'',
    id: 4,
  },
  {
    title: 'React JS E-Commerce *In progress*',
    description: "A modern e-commerce store built with React JS and Commerce JS, that was initially designed in Figma.",
    image: '/images/prod-8.png',
    tags: ['Figma', 'React', 'Commerce JS'],
    source: 'https://github.com/jackuson14/e-commerce',
    visit: '',
    sourceName: 'Github',
    visitName:'',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started foundation studies at University of Nottingham Malaysia studying Foundation of Engineering', },
  { year: 2018, text: 'Started undergraduate degree studies at University of Nottingham Malaysia studying Software Engineering', },
  { year: 2020, text: 'Started a 3-month internship as a React Native software developer at Fehux', },
  { year: 2021, text: 'Graduated from Univerisity of Nottingham', },
];

export const technologies = [
  {
    name: 'React/React Native',
    image: "https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/react/react.png",
    experience: '6 Months',
    percentage: 80,
    id:0,
  },
  {
    name: 'HTML/CSS',
    image: "https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/html/html.png",
    experience: '2 Years',
    percentage: 80,
    id:1,
  },
  {
    name: 'JavaScript',
    image: "https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/javascript/javascript.png",
    experience: '6 Months',
    percentage: 70,
    id:2,
  },
  {
    name: 'MySQL',
    image: "https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/mysql/mysql.png",
    experience: '1 Year',
    percentage: 80,
    id:3,
  },
  {
    name: 'Git',
    image: 'https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/git/git.png',
    experience: '2 Year',
    percentage: 80,
    id:4,
  },
  {
    name: 'MATLAB',
    image: 'https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/matlab/matlab.png',
    experience: '2 Year',
    percentage: 70,
    id:5,
  },
  {
    name: 'Django',
    image: 'https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/django/django.png',
    experience: '6 Months',
    percentage: 60,
    id:6,
  },
  {
    name: 'C',
    image: 'https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/c/c.png',
    experience: '6 Months',
    percentage: 60,
    id:7,
  },
  {
    name: 'Java',
    image: 'https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/java/java.png',
    experience: '1 Year',
    percentage: 80,
    id:8,
  },
  {
    name: 'Python',
    image: 'https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png',
    experience: '2 Years',
    percentage: 70,
    id:9,
  },
]